! leaf2.conf
hostname leaf2

!
vlan 20
   name server2_vlan
!
interface Vlan20
   description Gateway-for-server2
   ip address 172.16.20.254/24
!
interface Ethernet3
   description Link-to-server2
   switchport mode access
   switchport access vlan 20
!
interface Loopback0
   ip address 192.168.0.102/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.3/31
   bfd interval 300 min-rx 300 multiplier 3
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.9/31
   bfd interval 300 min-rx 300 multiplier 3
!
ip routing
!
router bgp 65012
   router-id 192.168.0.102
   neighbor 10.0.0.2 remote-as 65001
   neighbor 10.0.0.2 description Link-to-spine1
   neighbor 10.0.0.2 bfd
   neighbor 10.0.0.8 remote-as 65001
   neighbor 10.0.0.8 description Link-to-spine2
   neighbor 10.0.0.8 bfd
   !
   address-family ipv4
      network 192.168.0.102/32
      network 172.16.20.0/24
      neighbor 10.0.0.2 activate
      neighbor 10.0.0.8 activate
