! leaf1.conf
hostname leaf1

!
vlan 10
   name server1_vlan
!
interface Vlan10
   description Gateway-for-server1
   ip address 172.16.10.254/24
!
interface Ethernet3
   description Link-to-server1
   switchport mode access
   switchport access vlan 10
!
interface Loopback0
   ip address 192.168.0.101/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.1/31
   bfd interval 300 min-rx 300 multiplier 3
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.7/31
   bfd interval 300 min-rx 300 multiplier 3
!
ip routing
!
router bgp 65011
   router-id 192.168.0.101
   neighbor 10.0.0.0 remote-as 65001
   neighbor 10.0.0.0 description Link-to-spine1
   neighbor 10.0.0.0 bfd
   neighbor 10.0.0.6 remote-as 65001
   neighbor 10.0.0.6 description Link-to-spine2
   neighbor 10.0.0.6 bfd
   !
   address-family ipv4
      network 192.168.0.101/32
      network 172.16.10.0/24
      neighbor 10.0.0.0 activate
      neighbor 10.0.0.6 activate
