! leaf3.conf
hostname leaf3

!
vlan 30
   name server3_vlan
!
interface Vlan30
   description Gateway-for-server3
   ip address 172.16.30.254/24
!
interface Ethernet3
   description Link-to-server3
   switchport mode access
   switchport access vlan 30
!
interface Ethernet4
   description Link-to-server4
   switchport mode access
   switchport access vlan 30
!
interface Loopback0
   ip address 192.168.0.103/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.5/31
   bfd interval 300 min-rx 300 multiplier 3
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.11/31
   bfd interval 300 min-rx 300 multiplier 3
!
ip routing
!
router bgp 65013
   router-id 192.168.0.103
   neighbor 10.0.0.4 remote-as 65001
   neighbor 10.0.0.4 description Link-to-spine1
   neighbor 10.0.0.4 bfd
   neighbor 10.0.0.10 remote-as 65001
   neighbor 10.0.0.10 description Link-to-spine2
   neighbor 10.0.0.10 bfd
   !
   address-family ipv4
      network 192.168.0.103/32
      network 172.16.30.0/24
      neighbor 10.0.0.4 activate
      neighbor 10.0.0.10 activate
