! spine2.conf
hostname spine2

!
interface Loopback0
   ip address 192.168.0.2/32
!
interface Ethernet1
   description Link-to-leaf1
   no switchport
   ip address 10.0.0.6/31
   bfd interval 300 min-rx 300 multiplier 3
!
interface Ethernet2
   description Link-to-leaf2
   no switchport
   ip address 10.0.0.8/31
   bfd interval 300 min-rx 300 multiplier 3
!
interface Ethernet3
   description Link-to-leaf3
   no switchport
   ip address 10.0.0.10/31
   bfd interval 300 min-rx 300 multiplier 3
!
ip routing
!
router bgp 65001
   router-id 192.168.0.2
   neighbor 10.0.0.7 remote-as 65011
   neighbor 10.0.0.7 description Link-to-leaf1
   neighbor 10.0.0.7 bfd
   neighbor 10.0.0.9 remote-as 65012
   neighbor 10.0.0.9 description Link-to-leaf2
   neighbor 10.0.0.9 bfd
   neighbor 10.0.0.11 remote-as 65013
   neighbor 10.0.0.11 description Link-to-leaf3
   neighbor 10.0.0.11 bfd
   !
   address-family ipv4
      network 192.168.0.2/32
      neighbor 10.0.0.7 activate
      neighbor 10.0.0.9 activate
      neighbor 10.0.0.11 activate
