! leaf1.conf
hostname leaf1

!
vlan 10
   name server1_vlan
!
interface Vlan10
   description Gateway-for-server1
   ip address 172.16.10.254/24
!
interface Ethernet3
   description Link-to-server1
   switchport mode access
   switchport access vlan 10
!
interface Loopback0
   ip address 192.168.0.101/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.1/31
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.7/31
!
ip routing
!
router bgp 65001
   router-id 192.168.0.101
   maximum-paths 32
   neighbor SPINE_PEERS peer group
   neighbor SPINE_PEERS remote-as 65000
   neighbor SPINE_PEERS update-source Loopback0
   neighbor SPINE_PEERS ebgp-multihop 2
   neighbor 192.168.0.1 peer group SPINE_PEERS
   neighbor 192.168.0.2 peer group SPINE_PEERS
   !
   address-family ipv4
      neighbor SPINE_PEERS activate
      network 172.16.10.0/24
   !
!