! spine2.conf
hostname spine2

!
interface Loopback0
   ip address 192.168.0.2/32
!
interface Ethernet1
   description Link-to-leaf1
   no switchport
   ip address 10.0.0.6/31
!
interface Ethernet2
   description Link-to-leaf2
   no switchport
   ip address 10.0.0.8/31
!
interface Ethernet3
   description Link-to-leaf3
   no switchport
   ip address 10.0.0.10/31
!
ip routing
!
router bgp 65000
   router-id 192.168.0.2
   maximum-paths 32
   neighbor LEAF_PEERS peer group
   neighbor LEAF_PEERS remote-as-list 65001 65002 65003
   neighbor LEAF_PEERS update-source Loopback0
   neighbor LEAF_PEERS ebgp-multihop 2
   neighbor 192.168.0.101 peer group LEAF_PEERS
   neighbor 192.168.0.102 peer group LEAF_PEERS
   neighbor 192.168.0.103 peer group LEAF_PEERS
   !
   address-family ipv4
      neighbor LEAF_PEERS activate
   !
!