! spine1.conf
hostname spine1

!
interface Loopback0
   ip address 192.168.0.1/32
!
interface Ethernet1
   description Link-to-leaf1
   no switchport
   ip address 10.0.0.0/31
!
interface Ethernet2
   description Link-to-leaf2
   no switchport
   ip address 10.0.0.2/31
!
interface Ethernet3
   description Link-to-leaf3
   no switchport
   ip address 10.0.0.4/31
!
ip routing
!