! leaf3.conf
hostname leaf3

!
vlan 30
   name server3_4_vlan
!
interface Vlan30
   description Gateway-for-server3-4
   ip address 172.16.30.254/24
   ip ospf area 0.0.0.0
!
interface Ethernet3
   description Link-to-server3
   switchport mode access
   switchport access vlan 30
!
interface Ethernet4
   description Link-to-server4
   switchport mode access
   switchport access vlan 30
!
interface Loopback0
   ip address 192.168.0.103/32
   ip ospf area 0.0.0.0
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.5/31
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.11/31
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
ip routing
!
router ospf 1
   router-id 192.168.0.103
   passive-interface default
   no passive-interface Ethernet1
   no passive-interface Ethernet2
   no passive-interface Vlan30
   maximum-paths 32
!