! leaf2.conf
hostname leaf2

!
vlan 20
   name server2_vlan
!
interface Vlan20
   description Gateway-for-server2
   ip address 172.16.20.254/24
   ip ospf area 0.0.0.0
!
interface Ethernet3
   description Link-to-server2
   switchport mode access
   switchport access vlan 20
!
interface Loopback0
   ip address 192.168.0.102/32
   ip ospf area 0.0.0.0
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.3/31
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.9/31
   ip ospf network point-to-point
   ip ospf area 0.0.0.0
!
ip routing
!
router ospf 1
   router-id 192.168.0.102
   passive-interface default
   no passive-interface Ethernet1
   no passive-interface Ethernet2
   no passive-interface Vlan20
   maximum-paths 32
!