! leaf2.conf
hostname leaf2

!
vlan 20
   name server2_vlan
!
interface Vlan20
   description Gateway-for-server2
   ip address 172.16.20.254/24
!
interface Ethernet3
   description Link-to-server2
   switchport mode access
   switchport access vlan 20
!
interface Loopback0
   ip address 192.168.0.102/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.3/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.9/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
ip routing
!
router isis ISIS_NET
   net 49.0001.1921.6800.0102.00
   is-type level-2
   log-adjacency-changes
   bfd all-interfaces
   passive-interface Loopback0
   passive-interface Vlan20
   !
   address-family ipv4 unicast
      redistribute connected
      maximum-paths 32
   !
!
