! leaf1.conf
hostname leaf1

!
vlan 10
   name server1_vlan
!
interface Vlan10
   description Gateway-for-server1
   ip address 172.16.10.254/24
!
interface Ethernet3
   description Link-to-server1
   switchport mode access
   switchport access vlan 10
!
interface Loopback0
   ip address 192.168.0.101/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.1/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.7/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
ip routing
!
router isis ISIS_NET
   net 49.0001.1921.6800.0101.00
   is-type level-2
   log-adjacency-changes
   bfd all-interfaces
   passive-interface Loopback0
   passive-interface Vlan10
   !
   address-family ipv4 unicast
      redistribute connected
      maximum-paths 32
   !
!
