! leaf3.conf
hostname leaf3

!
vlan 30
   name server3_4_vlan
!
interface Vlan30
   description Gateway-for-server3-4
   ip address 172.16.30.254/24
!
interface Ethernet3
   description Link-to-server3
   switchport mode access
   switchport access vlan 30
!
interface Ethernet4
   description Link-to-server4
   switchport mode access
   switchport access vlan 30
!
interface Loopback0
   ip address 192.168.0.103/32
!
interface Ethernet1
   description Link-to-spine1
   no switchport
   ip address 10.0.0.5/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
interface Ethernet2
   description Link-to-spine2
   no switchport
   ip address 10.0.0.11/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
ip routing
!
router isis ISIS_NET
   net 49.0001.1921.6800.0103.00
   is-type level-2
   log-adjacency-changes
   bfd all-interfaces
   passive-interface Loopback0
   passive-interface Vlan30
   !
   address-family ipv4 unicast
      redistribute connected
      maximum-paths 32
   !
!
