! spine2.conf
hostname spine2

!
interface Loopback0
   ip address 192.168.0.2/32
!
interface Ethernet1
   description Link-to-leaf1
   no switchport
   ip address 10.0.0.6/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
interface Ethernet2
   description Link-to-leaf2
   no switchport
   ip address 10.0.0.8/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
interface Ethernet3
   description Link-to-leaf3
   no switchport
   ip address 10.0.0.10/31
   bfd interval 300 min-rx 300 multiplier 3
   isis bfd
   isis enable ISIS_NET
   isis circuit-type level-2
!
ip routing
!
router isis ISIS_NET
   net 49.0001.1921.6800.0002.00
   is-type level-2
   log-adjacency-changes
   bfd all-interfaces
   passive-interface Loopback0
   !
   address-family ipv4 unicast
      redistribute connected
      maximum-paths 32
   !
!
